include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - sort_pub_dependencies
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
