name: cccc
description: This is a description
publish_to: "none"

version: 0.0.2

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.0.0

  # Core
  cupertino_icons: ^1.0.4
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  flutter_svg: ^1.0.0
  logger: ^1.1.0
  flutter_lints: ^1.0.4
  http: ^0.13.4
  intl: ^0.17.0

  # Google & Firebase
  firebase_core: ^1.10.0
  cloud_firestore: ^3.1.4
  firebase_auth: ^3.3.3
  google_sign_in: ^5.2.1

  # State Management
  flutter_riverpod: ^1.0.2

  # Plaid
  plaid_flutter: ^2.1.4

  # UI
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  freezed: ^1.1.0
  json_serializable: ^6.1.3

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/RobotoMono-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/RobotoMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/RobotoMono-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoMono-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMono-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoMono-BoldItalic.ttf
          weight: 700
          style: italic
  assets:
    - assets/svg/
