name: cccc
description: Credit Card Calorie Counter
publish_to: "none"

version: 0.0.13

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.13
  cupertino_icons: ^1.0.4
  firebase_auth: ^3.3.15
  firebase_core: ^1.15.0
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_riverpod: ^1.0.3
  flutter_svg: ^1.0.3
  freezed_annotation: ^2.0.1
  google_ml_kit: ^0.8.0
  google_sign_in: ^5.3.0
  http: ^0.13.4
  image_picker: ^0.8.5
  intl: ^0.17.0
  json_annotation: ^4.4.0
  keyboard_actions: ^3.4.7
  local_auth: ^2.0.0
  logger: ^1.1.0
  plaid_flutter: ^2.2.1
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0
  visibility_detector: ^0.2.2
dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  freezed: ^2.0.2
  json_serializable: ^6.1.6

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/RobotoMono-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/RobotoMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/RobotoMono-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoMono-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMono-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoMono-BoldItalic.ttf
          weight: 700
          style: italic
  assets:
    - assets/svg/
    - assets/pictures/
