name: cccc
description: Credit Card Calorie Counter
publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.2.5
  firebase_auth_mocks: ^0.10.3
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  flutter_svg: ^1.1.6
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.2.0
  go_router: ^6.0.1
  google_mlkit_text_recognition: ^0.5.0
  google_sign_in: ^5.4.3
  http: ^0.13.5
  image_picker: ^0.8.6+1
  intl: ^0.17.0
  json_annotation: ^4.8.0
  keyboard_actions: ^4.1.0
  local_auth: ^2.1.3
  logger: ^1.1.0
  mockito: ^5.3.2
  plaid_flutter: ^3.0.1
  shared_preferences: ^2.0.17
  visibility_detector: ^0.3.3
dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  go_router_builder: ^1.0.15
  integration_test:
    sdk: flutter
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/RobotoMono-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/RobotoMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/RobotoMono-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoMono-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMono-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoMono-BoldItalic.ttf
          weight: 700
          style: italic
  assets:
    - assets/svg/
    - assets/pictures/
