name: plaid_flutter_example
description: Demonstrates how to use the plaid_flutter plugin.
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  plaid_flutter: ^2.1.4

flutter:
  uses-material-design: true
