import 'dart:convert';

/// Information describing the intent of the transaction. Most relevant for
/// personal finance use cases, but not limited to such use cases. The field is
/// currently in beta.
///
/// The complete category can be generated by concatenating primary and
/// detailed categories.
///
/// This feature is currently in beta – to request access, contact
/// transactions-feedback@plaid.com.
class PersonalFinanceCategory {
  PersonalFinanceCategory({
    required this.primary,
    required this.detailed,
  });

  final String primary;
  final String detailed;

  PersonalFinanceCategory copyWith({
    String? primary,
    String? detailed,
  }) {
    return PersonalFinanceCategory(
      primary: primary ?? this.primary,
      detailed: detailed ?? this.detailed,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'primary': primary,
      'detailed': detailed,
    };
  }

  factory PersonalFinanceCategory.fromMap(Map<String, dynamic> map) {
    return PersonalFinanceCategory(
      primary: map['primary'],
      detailed: map['detailed'],
    );
  }

  String toJson() => json.encode(toMap());

  factory PersonalFinanceCategory.fromJson(String source) =>
      PersonalFinanceCategory.fromMap(json.decode(source));

  @override
  String toString() =>
      'PersonalFinanceCategory(primary: $primary, detailed: $detailed)';

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is PersonalFinanceCategory &&
        other.primary == primary &&
        other.detailed == detailed;
  }

  @override
  int get hashCode => primary.hashCode ^ detailed.hashCode;
}
