import 'package:freezed_annotation/freezed_annotation.dart';

part 'personal_finance_category.freezed.dart';
part 'personal_finance_category.g.dart';

/// Information describing the intent of the transaction. Most relevant for
/// personal finance use cases, but not limited to such use cases. The field is
/// currently in beta.
///
/// The complete category can be generated by concatenating primary and
/// detailed categories.
///
/// This feature is currently in beta – to request access, contact
/// transactions-feedback@plaid.com.
@Freezed()
class PersonalFinanceCategory with _$PersonalFinanceCategory {
  const factory PersonalFinanceCategory({
    required String primary,
    required String detailed,
  }) = _PersonalFinanceCategory;

  factory PersonalFinanceCategory.fromJson(Map<String, dynamic> json) =>
      _$PersonalFinanceCategoryFromJson(json);
}
